### ISSUE TITLE
The name prefix should be change when a user chooses a different identity

### ISSUE THREAD

**Issue by zhtaoxiang** [zhehaowang/ndnfit#1]
Now the prefix is hard coded in NDNFitCommon.java. Need to be configured every time a user chooses a different identity.

**Comment by zhehaowang** [comment]
This is currently handled by this <a href="https://github.com/zhehaowang/ndnfit/blob/master/app/src/main/java/ucla/remap/ndnfit/NDNFitCommon.java#L23-L26">function</a>, called <a href="https://github.com/zhehaowang/ndnfit/blob/master/app/src/main/java/ucla/remap/ndnfit/MainActivity.java#L140">here</a> as well as <a href="https://github.com/zhehaowang/ndnfit/blob/master/app/src/main/java/ucla/remap/ndnfit/MainActivity.java#L227">here</a>. Fixed in <a href="https://github.com/zhehaowang/ndnfit/commit/efbab971864b33db2c86af52fd8bfb806c5b1d73">this commit</a> 7 days ago. Let me know if you suspect there's still a problem.

Also, for now the identity choice is a one-time only thing; there's no UI interactions to clear a selected identity.
